version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - creator-net

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/creators-platform
      - JWT_SECRET=c5fc11c489e3b5d0ce2fdfba8d08e56e6995143abff78038022812319a9412b8
      - JWT_EXPIRE=7d
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - creator-net

  client:
    build: 
      context: ./client
      args:
        - VITE_API_URL=http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - creator-net

volumes:
  mongo-data:

networks:
  creator-net:
    driver: bridge
