version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./server/.env
      - ./server/.env.docker
    depends_on:
      - mongo

  client:
    build: 
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
